In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    # creating element on device
    x = torch.ones(5, device=device)
    # moving elements to device
    y = torch.ones(5)
    y = y.to(device)
    # moving back to cpu
    z = x + y # Operation is still done on the GPU
    z = z.to("cpu")

# Tensor 
types of tensor includes
1. torch.empty
2. torch.ones
3. torch.randn
4. torch.randint


In [3]:
# Prints a 1 dimensional array of tensor
x = torch.empty(3)
print(x)
print(x.dtype)
print(x.size())
print('-'*80)

# Prints a 2x3 dimenstional array of tensor
x = torch.ones(2,3, dtype=torch.int32)
print(x)        # Prints the tensor
print(x.dtype)  # Prints the dtype of the elements
print(x.size()) # Prints the shape of tensor

tensor([0., 0., 0.])
torch.float32
torch.Size([3])
--------------------------------------------------------------------------------
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.int32
torch.Size([2, 3])


## Custom Tensor

In [9]:
# Custom 1 dimensional tensor
x = torch.tensor([2.5,0.1])
print(x)
print(x.dtype)
print(x.size())

tensor([2.5000, 0.1000])
torch.float32
torch.Size([2])


# Operations on Tensor

In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

# Addition
z = x + y # == z = x.add(y)
print(z)

# In place operation
# this will replace the elements in y
y.add_(x)

tensor([[1.5073, 0.8410],
        [0.0988, 1.3570]])


tensor([[1.5073, 0.8410],
        [0.0988, 1.3570]])

# Slicing

In [15]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0203, 0.1089, 0.8402],
        [0.9614, 0.7788, 0.2405],
        [0.0665, 0.0696, 0.9140],
        [0.0302, 0.2248, 0.9032],
        [0.0241, 0.8712, 0.8879]])


In [21]:
# First Column
# Row Vector
print("Row vector")
print(x[:, 0])

# Transpose for Column vector
print("Column Vector")
print(x[:, 0].unsqueeze(dim=0).permute(1,0))

Row vector
tensor([0.0203, 0.9614, 0.0665, 0.0302, 0.0241])
Column Vector
tensor([[0.0203],
        [0.9614],
        [0.0665],
        [0.0302],
        [0.0241]])


In [22]:
# First row
# Row Vector
print("Row vector")
print(x[0, :])

# Transpose for Column vector
print("Column Vector")
print(x[0, :].unsqueeze(dim=0).permute(1,0))

Row vector
tensor([0.0203, 0.1089, 0.8402])
Column Vector
tensor([[0.0203],
        [0.1089],
        [0.8402]])


## Getting the value of the tensor 
Only when the tensor has a single element

In [26]:
z = x[1,1]
print(z)
print(z.item())

tensor(0.7788)
0.7787730097770691


# Reshaping Tensor

In [27]:
x = torch.rand(4,4)
print(x)

tensor([[0.5885, 0.9966, 0.8519, 0.3416],
        [0.0889, 0.2146, 0.9760, 0.9309],
        [0.8226, 0.7531, 0.3415, 0.4749],
        [0.0890, 0.1638, 0.4877, 0.5143]])


In [31]:
# Single vector
# Number in view must commute with the total number of
# elements in the tensor
y = x.view(16)
print(y)
print(y.size())

# Tensor auto decide
y = x.view(-1, 8)
print(y)
print(y.size())

tensor([0.5885, 0.9966, 0.8519, 0.3416, 0.0889, 0.2146, 0.9760, 0.9309, 0.8226,
        0.7531, 0.3415, 0.4749, 0.0890, 0.1638, 0.4877, 0.5143])
torch.Size([16])
tensor([[0.5885, 0.9966, 0.8519, 0.3416, 0.0889, 0.2146, 0.9760, 0.9309],
        [0.8226, 0.7531, 0.3415, 0.4749, 0.0890, 0.1638, 0.4877, 0.5143]])
torch.Size([2, 8])


# Tensor to Numpy conversion

In [32]:
import torch
import numpy as np

## Tensor to Numpy

In [35]:
a = torch.ones(5)
print(a)
b = a.numpy() # this will convert a to numpy
print(b)
# BEWARE: This will cause the values to share the same memory location
# i.e. changing one value will change another one
# e.g.
print("After adding 1 to Torch Tensor")
a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
After adding 1 to Torch Tensor
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Numpy to Tensor

In [38]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

# These will also share the same memory location
a += 1
print("After adding 1 to numpy array")
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
After adding 1 to numpy array
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
