In [1]:
import numpy as np

# The basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimenstion of Np array
a.ndim

1

In [9]:
# get shape
print("shape of a: ", a.shape)
print("shape of b: ", b.shape)

shape of a:  (3,)
shape of b:  (2, 3)


In [10]:
# Get data types
print("data type of a: ", a.dtype)

data type of a:  int32


In [11]:
# Get size of element
print("Size of a: ", a.itemsize)

Size of a:  4


In [13]:
#Get total size
print("Total size of a : ", a.nbytes)

Total size of a :  12


# Assessing/Changing specific elements, rows, columns

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get specific element
a[0,2]

3

In [18]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# get specific column
a[:,2]

array([ 3, 10])

In [20]:
# steps
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
# Edit
a[1,5] = 30
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 30 14]]


In [28]:
# 3D Example
b = np.array([[[1,2,0],[3,4,0]],[[5,6,0],[7,8,0]]])
print(b)

[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]]


In [29]:
print(b.shape)

(2, 2, 3)


In [31]:
print(b[:,1,1])

[4 8]


# Initialise Different Types of Arrays

In [32]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# All ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [38]:
# Random Numbner between 0, 1
np.random.rand(4)

array([0.42897141, 0.87002333, 0.02472064, 0.37107284])

In [55]:
# Random int value [0,10)
np.random.randint(10, size=(3,3))

array([[1, 8, 1],
       [9, 7, 4],
       [0, 2, 8]])

In [56]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [62]:
arr = np.array([[1,2,3]])
print(arr)
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


# making a copy

In [63]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [69]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [65]:
a*2

array([2, 4, 6])

In [66]:
a/2

array([0.5, 1. , 1.5])

In [68]:
a+=2
print(a)

[5 6 7]


In [70]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

## Linear Algebra

In [72]:
#Matrix dot product
a = np.ones((2,3))
print(a)


b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [73]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [74]:
# Detminant
c = np.identity(3)
np.linalg.det(c)

1.0

In [75]:
# inverse
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
# eigenvalue
np.linalg.eigvals(c)

array([1., 1., 1.])

# Statistics

In [83]:
a = np.array([[1,2,10],[4,5,6]])

In [84]:
#min
np.min(a, axis=1)

array([1, 4])

In [85]:
np.min(a,axis=0)

array([1, 2, 6])

In [86]:
np.sum(a, axis=1)

array([13, 15])

# Reorganising Array

In [89]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [90]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [92]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [100]:
after = before.reshape((-1,))
print(after)

[1 2 3 4 5 6 7 8]


In [101]:
# vertically stacking array
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

# Element Wise Operations

In [9]:
a1 = np.array([[1,2,3,4],
               [5,6,7,8]])
a2 = np.array([[10,20,30,40],
               [50,60,70,80]])

print("a1")
print(a1)
print("a2")
print(a2)

a1
[[1 2 3 4]
 [5 6 7 8]]
a2
[[10 20 30 40]
 [50 60 70 80]]


In [10]:
# Elementwise Multiplication
print(np.multiply(a1,a2))

[[ 10  40  90 160]
 [250 360 490 640]]
